language: php

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  - bin
  - vendor

before_script:
  - composer self-update
  - composer install --prefer-source --optimize-autoloader --no-interaction

script:
  - bin/phpunit --coverage-text
