language: php

php:
  - 5.4
  - 5.5
  - 5.6

cache:
  - bin
  - vendor

before_script:
  - composer self-update
  - composer install --prefer-source --optimize-autoloader --no-interaction

script:
  #Â - bin/phpunit --coverage-text
  - echo "not tested... yet"
